name: endpoints
version: 0.1.0
author: Dart Team <misc@dartlang.org>
description: Library for exposing Dart server-side APIs.
homepage: https://github.com/dart-lang/dart_endpoints
environment:
  sdk: '>=1.5.0 <2.0.0'
dependencies:
  crypto: ">=0.9.0 <0.10.0"
  googleapis: '>=0.3.0 <0.5.0'
  uri: '>=0.9.3 <0.10.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
  shelf: '>=0.5.6 <0.6.0'
  shelf_route: '>=0.11.0+1 <0.12.0'
  appengine: '>=0.2.3 <0.3.0'