name: endpoints
version: 0.0.1
author: Gerwin Sturm
description: Implementation of Google Cloud Endpoints
homepage: https://dart-endpoints.appspot.com/

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  appengine: any
  memcache: any
  shelf_appengine: any
  google_oauth2_v2_api: '>=0.4.13 <0.5.0'

dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
  browser: any
  mydartapi_v1_api:
    path: ../deps/dart_mydartapi_v1_api_client

dependency_overrides:
  shelf_appengine:
    git:
      url: git@github.com:dart-lang/shelf_appengine.git
      ref: 0-1-dev
  appengine:
    git:
      url: git@github.com:dart-lang/appengine.git
      ref: v0.1
  cloud_datastore:
    git:
      url: git@github.com:dart-lang/cloud_datastore.git
      ref: v0.1
  memcache:
    git:
      url: git@github.com:dart-lang/memcache.git
      ref: v0.1
