name: rpc
version: 0.1.0
author: Dart Team <misc@dartlang.org>
description: Library for exposing Dart server-side APIs.
homepage: https://github.com/dart-lang/rpc
environment:
  sdk: '>=1.8.3 <2.0.0'
dependencies:
  crypto: ">=0.9.0 <0.10.0"
  uri: '>=0.9.3 <0.10.0'
dev_dependencies:
  unittest: '>=0.11.0 <0.12.0'
  shelf: '>=0.5.6 <0.6.0'
  shelf_route: '>=0.11.0+1 <0.12.0'
